### ISSUE TITLE
Multiple filesystem arguments not respected

### ISSUE THREAD

**Issue by treydock** [zfsnap/zfsnap#57] opened 2014-11-22 03:15 UTC
I'm using the 2.0 beta and have found that passing multiple filesystems at the command line results in only the first one listed being snapshotted.

Example:

```
# /usr/sbin/zfsnap snapshot -s -S -v -a 1d tank/home tank/apps
/sbin/zfs snapshot  tank/home@2014-11-21_21.14.05--1d ... DONE
```

I've tried placing "-a" option in front of each filesystem argument but the result in the same.

**Comment by Alexqw** [comment] 2015-01-12 14:36
@treydock I've testing this out on my systems, and I can't reproduce your bug. Are you running the latest master? Also, which OS are you on?

---Alex

**Comment by treydock** [comment] 2015-01-14 02:33
@Alexqw This install is on commit cc75d74 dated 11/11/2014 and is on CentOS 6.5.  I'll update my install and see if the results are any different

**Comment by Alexqw** [comment] 2015-01-27 15:01
Closing as I am unable to reproduce the problem on any of the environments I test on.

@treydock Please reopen if this is still a problem for you on latest master.

---Alex

**Closed by Alexqw** 2015-01-27 15:01 UTC
